Display V2
ChatTriggers/ctjs pull request #50
Opened 2023-06-30 23:19 UTC by DalwynWasTaken

Repurpose Display to use the more up-to-date rendering principles by using Text and the philosophies it has. 

Align enum has been moved to Text where it is actually used. Align has been added to Text to actually work alongside Display

Order enum has been renamed from UP and DOWN to NORMAL and REVERSED to indicate the changes made internally to rendering. Order now changes the order but not the position of the Display.

RegisterType enum has been removed as draw is now called by the module creator instead of internally. Removed a bunch of references to Display since it no longer internally renders everything.

DisplayLine has been removed as it was a glorified Text with some triggers.

Fixed a known memory sink when setting lines with a string. Adding and setting now should use a more optimized way of setting the text.

2023-06-30 23:21 UTC, DalwynWasTaken commented
If you want me to write the stuff that would impact CT module developers into the migration docs, please tell me.

This is a drastic change to the way Display used to function but it allows for a lot more flexibility. 
DisplayLine has triggers attached to itself, this could be something interesting to add to Texts in general?

2023-06-30 23:32 UTC, DalwynWasTaken reviewed
Formatting fixup

2023-06-30 23:32 UTC, DalwynWasTaken commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/Display.kt
> +}
TODO: Add an extra line here

2023-06-30 23:32 UTC, DalwynWasTaken commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Text.kt
> +
Remove this extra line

2023-07-02 18:22 UTC, mattco98 requested changes

2023-07-02 18:22 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Text.kt
> +    @JvmOverloads
Remove `@JvmOverloads` here

2023-07-02 20:20 UTC, merged